language: csharp
dist: bionic
dotnet: 3.1.300

matrix:
  fast_finish: true
  
  include:
    - os: linux
      mono: latest
    - os: osx
      osx_image: xcode11.3
      mono: latest

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

script:
  - ./fake build
