image:
  - Visual Studio 2015
  - Visual Studio 2017

install:
  - dotnet tool install fake-cli -g

build_script:
  - fake build

on_finish:
  - ps: >-
      $testResults = @(
         '.\bin\Expecto.Tests.TestResults.xml'
         '.\bin\Expecto.Tests.CSharp.TestResults.xml'
      );
      Foreach ($path in $testResults) {
        If (Test-Path $path) {
          (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$env:APPVEYOR_JOB_ID", (Resolve-Path $path));
        }
      }
